### PR TITLE
Add Zigbee joining to Domoticz interface

### PR DESCRIPTION
**Pull request by JanJaapKo**
add switching of 'permit_join' to web interface, so you can switch joining on and off via Domoticz

### CODE REVIEW

**Comment by JanJaapKo** [comment]
@stas-demydiuk I created this pull request but am not sure if I did it correctly. It is about adding the possibility to switch 'permit_join' of the Zigbee bridge from Domoticz, so it allows easy switching off when all devices are added. So I do not accidentally add new devices form my neighbors ;)

**Comment by stas-demydiuk** [comment]
@JanJaapKo Thank you for the PR! Great idea to make possible to control `permit_join` from Domoticz, I'm just thinking would it be more convenient if it will be just switch in Domoticz instead of setting in plugin

**Comment by JanJaapKo** [comment]
Hi @stas-demydiuk  I put it in the plugin part for 2 reasons:
- it is not something you do daily, adding devices. So to limit the amount of switches, I choose to put it in the plugin
- the 'joining' is a property of the bridge, same as the other parameters in the plugin

I am working on the addition in Zigbee2MQTT to make the switching of the LED work over MQTT so it can act as an indication that joining is permited (not finished yet)

**Comment by stas-demydiuk** [comment]
Yes, make sense. Thank you for the PR!

**Pull request merged**
