### PR TITLE
Add support for RGBW bulbs...

### PR DESCRIPTION
**Pull request by d-EScape**
... like Philips White and color ambiance.
For these bulbs you can now choose between rgb or color temperature setting.

As with many rgb->xy->rgb calculations the returned color value is not exact, but usable for the sliders and  rgb color picker in Domoticz.

Unfortunately I had to remove the (color) transition time because it would make Domoticz think the color was set anywhere between the start and end color value during the transition. Already posted an Issue at Zigbee2mqtt (actually zigbee-shepherd-converters) project.

### CODE REVIEW

**Comment by d-EScape** [comment]
Forgot to mention: zigbee2mqtt does not yet provide the ColorMode in its acknowledgement message, so Domoticz will still think you set the color temperature using the rgb picker (my device file assumes rgb if no mode is provided).
I submitted a pull request to Zigbee-shepherd-converters that will provide the ColorMode. If/when it gets merged the Domoticz plugin can use it and will show the right picker (rgb or ct).

For the brave that can't wait, you can manually edit the Zigbee-shepherd-converter file with de modification in the pull request:
https://github.com/Koenkk/zigbee-shepherd-converters/pull/154

**Comment by stas-demydiuk** [comment]
@d-EScape Thanks for the great PR! Do you know will it work for other similar devices? (on/off, brightness, color temperature, color xy)

**Comment by d-EScape** [comment]
Glad to contribute :D These where features that keep me from ditching my Philips hub completely ;-)

Zigbee2mqtt should treat any rgbww bulb the same and these are common commands, so I see no reason why they should not work with other brands than Philips. I have no wat to test this though.

2 things I would like to add/ask concerning this device type and my experience so far:
- The transition problem in zigbee2mqtt has been fixed in the dev branch, so I can restore transition functionality in the near future. However... wouldn't it be better to have a generic 'transition time for lights' parameter in the plugin settings? Hardcoding them in de converter seems a bit harsh :S
- I think the color temperature in the existing dimmable_ct_bulb_adapter.py might be wrong. From what I get from the Zigbee-shepherd-converters it is not simply (0-255) -> (0-500) conversion. I took my method from reversing the Zigbee-shepherd-converters calculation. The rgb conversion in color_light.py didn't work for me either. Maybe a general calculation module would be better(?) Can you include something https://github.com/benknight/hue-python-rgb-converter ?

**Comment by stas-demydiuk** [comment]
@d-EScape 
- I think to have plugin wide setting for transition is a good idea since we have no way to make it device specific.
- Unfortunately I don't have any CT bulb to test how it looks like on real device, so any contribution is extremely welcome

**Comment by d-EScape** [comment]
I just did a little experiment with the module I mentioned but unfortunately the sent en received color values are even further apart than by just leaving the rgb->xy conversion to zigbee2mqtt and converting the xy value back in the plugin (method in this commit). At least with the 'Hue white and color ambiance' bulbs I use.

I don't own any ct devices either, but had a look at the Zigbee-shepherd-converter that does:
```
                if (key === 'color_temp_percent') {
                    value = Number(value) * 3.46;
                    value = Math.round(value + 154).toString();
                }
```
So it looks like the conversion is adding 154 and 346 is actually 100% warm white in zigbee2mqtt.

**Comment by JanJaapKo** [comment]
Hi guys,

I ran some tests with my IKEA TRADFRI LED1624G9 bulbs. Setting the color via the black and white slider works, although it produces some grey light (surprised actually to see such a light come out of a bulb....)
image
Is this the slider how to set the color temperature? Because I would have expected it to run between cold and warm white.

One remark though: updating via the above slider takes long for the lights to react, if at all. Setting a color via the wheel is much faster

**Comment by d-EScape** [comment]
Hi Jan-Jaap,

Although the adapter should work with other rgbw lights, I did not change the adapter settings of other lights to use this new adapter. Dit you change the __init__.py file in the adapters directory yourself?

If not, please try the following:
In the <this plugins root>/adapters/__init__.py file replace the adapter reference for the LED1624G9 (line 47)
from:
`'LED1624G9': RGBAdapter, `   
to:
`'LED1624G9': RGBWAdapter,`

Please share your findings. If compatibility for this lights is confirmed it can be changed in the source.

**Comment by JanJaapKo** [comment]
Hi @d-EScape ,

The RGBW adapter doesn't work as-is for the IKEA light. The commands for the dolor temperature are just ignored apparently. I think the way the light reports back, it is just not supported, see the logging below.

I do notice however that the colortemp device's xy to rgb conversion is better than in the color light how I made it (the feedback in the color light just doesn't seem to work, the color picker is always at center when you reopen it and with the RGBW/colortemp it nicely remains at the set value). So I will make a separate pull request to fix that.

`2018-12-16 11:51:32.417 (Zigbee2MQTT) MqttClient::Ping
2018-12-16 11:51:42.434 (Zigbee2MQTT) MqttClient::Ping
2018-12-16 11:51:48.295 (Zigbee2MQTT) onCommand: Set Color, level (77) Color:{"b":0,"cw":204,"g":0,"m":2,"r":0,"t":51,"ww":51}
2018-12-16 11:51:48.295 (Zigbee2MQTT) Sending to ZigBee:{"state": "ON", "color_temp": 223, "brightness": 196}
2018-12-16 11:51:48.296 (Zigbee2MQTT) MqttClient::Publish zigbee2mqtt/Schemerlamp1/set ({"state": "ON", "color_temp": 223, "brightness": 196})
2018-12-16 11:51:48.665 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Schemerlamp1 {'state': 'ON', 'color': {'y': 0.345, 'x': 0.6}, 'brightness': 196}
2018-12-16 11:51:48.665 (Zigbee2MQTT) Received heartbeat message from device "Zigbee2MQTT - Schemerlamp1 (Link Quality)"
2018-12-16 11:51:48.665 (Zigbee2MQTT) zigbee device:0xd0cf5efffe2901cb sent message:{'state': 'ON', 'color': {'y': 0.345, 'x': 0.6}, 'brightness': 196}
2018-12-16 11:51:48.666 (Zigbee2MQTT) update domticz device: '{'sValue': '76', 'nValue': 1, 'Color': '{"g": 117, "m": 3, "b": 67, "r": 255}'}'
2018-12-16 11:51:48.285 Status: setcolbrightnessvalue: ID: 70, bri: 77, color: '{m: 2, RGB: 000000, CWWW: cc33, CT: 51}'
2018-12-16 11:51:49.328 (Zigbee2MQTT) MQTT message: zigbee2mqtt/Schemerlamp1 {'state': 'ON', 'color': {'y': 0.345, 'x': 0.6}, 'brightness': 196}
2018-12-16 11:51:49.328 (Zigbee2MQTT) Received heartbeat message from device "Zigbee2MQTT - Schemerlamp1 (Link Quality)"
2018-12-16 11:51:49.328 (Zigbee2MQTT) zigbee device:0xd0cf5efffe2901cb sent message:{'state': 'ON', 'color': {'y': 0.345, 'x': 0.6}, 'brightness': 196}
2018-12-16 11:51:49.329 (Zigbee2MQTT) update domticz device: '{'sValue': '76', 'nValue': 1, 'Color': '{"g": 117, "m": 3, "b": 67, "r": 255}'}'
2018-12-16 11:51:52.398 (Zigbee2MQTT) MqttClient::Ping
2018-12-16 11:52:02.413 (Zigbee2MQTT) MqttClient::Ping
`

**Comment by d-EScape** [comment]
Thats unfortunate. It is still possible that zigbee-shepherd-converters doesn't handle the (raw) Zigbee messages to and from the bulb correctly. You might be able to find out from the debug logging in zigbee2mqtt. If the bulb doesn't take and/or return any color temperature value then it would need a separate translation to use the color temperature sliders in Domoticz. Either in Zigbee-shepherd-converters or in the plugin.
I have no color lights to test this, but it looks like you know your stuff ;-)

The one Ikea dimmable white light I own is a disappointment (lowest dim level is ridiculously bright) so i'm not planning to expand my Tradfri 'collection'.

**Comment by JanJaapKo** [comment]
the log doesn't show any hints to something going wrong (see below). The lights themselves just seem to ignore it. The converter in Zigbee shepherd does specify also color temperature. 

I am quite satisfied with the color bulb (I have 2 of them). Dims pretty good (to my standards at least) and it turns nicely in all kinds of colors. 

`Dec 16 12:46:26 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:46:26 Zigbee: disabling joining new devices.
Dec 16 12:47:00 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:00 Zigbee publish to '0xd0cf5efffe2901cb', lightingColorCtrl - moveToColorTemp - {"colortemp":449,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null
Dec 16 12:47:00 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:00 Zigbee publish to '0xd0cf5efffe2901cb', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null
Dec 16 12:47:01 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:01 MQTT publish, topic: 'zigbee2mqtt/Schemerlamp1', payload: '{"state":"ON","brightness":104,"color":{"x":0.162,"y":0.083}}'
Dec 16 12:47:01 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:01 Zigbee publish to '0xd0cf5efffe2901cb', genLevelCtrl - moveToLevelWithOnOff - {"level":2,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null
Dec 16 12:47:01 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:01 MQTT publish, topic: 'zigbee2mqtt/Schemerlamp1', payload: '{"state":"ON","brightness":104,"color":{"x":0.162,"y":0.083}}'
Dec 16 12:47:01 raspberrypi npm[574]:   zigbee2mqtt:info 2018-12-16 12:47:01 MQTT publish, topic: 'zigbee2mqtt/Schemerlamp1', payload: '{"state":"ON","brightness":2,"color":{"x":0.162,"y":0.083}}'
`

**Comment by JanJaapKo** [comment]
I ran Zigbee2mqtt with loglevel debug, but the ouput of `sudo journalctl -u zigbee2mqtt.service -f` doesn't really change. Am I looking to the right place?

I see the messages to the zigbee network specifiying color_temp but the lights do not really change (I started it at green or blue) and sometimes the intensity seems to change.

I also don't really see a slider but a color wheel for the temperature (also not as I would entirely expect it but should work anyhow)
image

**Comment by d-EScape** [comment]
The journalctl command you are using is fine.
You can get some more logging by adding this line to the service section of the service file (mine is /etc/systemd/system/zigbee2mqtt.service) :

Environment=DEBUG=*

This will show the debug logging of zigbee2mqtt AND the submodules like Zigbee-shepherd.

**Pull request merged**
