### PR TITLE
adding detection of update available and mode on pluging

### PR DESCRIPTION
**Pull request by JanJaapKo**
Hi @stas-demydiuk ,

I made some first changes after some experiments with OTA to implement enhancement #282 . My idea is to have a mode (like the 'permit join') that allows zigbee2mqtt to run an update when a device reports that it has firmware updates available. This status is added to the normal status updates that are published to topic `zigbee2mqtt\<friendly_name>` in the payload as element `update_available` with values true and false.

So I added detection (now it only logs it) in the devices/device.py class but am not sure how to continue from there, as I cannot get the value of `self.OTA_enabled` from the `BasePlugin` class to the device base class. Hope you can provide some advice there.

I wanted to stay away from a design where the `self.OTA_enabled` would trigger a query on all devices whether they have an update available. The downside of the above is that it will take a state change on the device so that it reports its status so you are never sure you have had them all. On the other hand, querying devices may not work for battery powered devies that go to sleep.

I ran a small test on my network of 10 devices, updating 1 of them did not influence performance what so ever. But I have only 3 devices left that actually can update, so I'm saving them for the final test......

### CODE REVIEW

**Comment by stas-demydiuk** [comment]
@JanJaapKo I would suggest to implement required feature via UI that plugin will provide soon. I've already added couple examples like renaming device and setting its state. See code in [network-map](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/tree/network-map) branch

**Comment by JanJaapKo** [comment]
Hi @stas-demydiuk the custom pages look brilliant! Networkmap nicely displayed, nice table (hint: add manufacturer to model column). Would be great to add to the devices table a column with the update status with a button to trigger sending the actual update command. I'll see if I get rund to that (js ain't my best language though.....).

**Comment by JanJaapKo** [comment]
Hi @stas-demydiuk 

I've got it working from the frontend, with the following remarks:
- I haven't figured out how to hide the 'download' button for devices that do not have an update available
- I want to have a report back to the modal form if the update started or not (would at least notify user of no update available or not supported) but not sure how to do this
- I added also the 'vendor' to the table but it gives an error (for the coordinator I presume) but it did not do that for model info, which in my case is also missing for the coordinator. How did you work around  that?

**Comment by stas-demydiuk** [comment]
Thanks, will include this change to #290

**Pull request closed without merging**
