### PR TITLE
Add temperature support for MCCGQ11LM

### PR DESCRIPTION
**Pull request by martin-g-it**

### CODE REVIEW

**Comment by d-EScape** [comment]
The MCCGQ01LM uses the same adapter but does not seem to have a temperature sensor. So I think think a separate adapter is needed. Already have it running on my setup and I could make it a pr if you want. Note that the temperature reading is about 4 degrees to high on both my MCCGQ11LM.

**Comment by martin-g-it** [comment]
Didn't think about the dependency, makes sense to create a different adapter then.. will you take care of this @d-EScape?

I also have some deviations in temperature on some devices, some have +3, some -4, but this can be managed in the configuration.yaml via the temperature_calibration feature.

**Comment by d-EScape** [comment]
Good tip about calibration, thanks. Didn’t think of that.
I will push a pr this weekend.

**Comment by d-EScape** [comment]
I submitted PR #566
You should probably close this one, otherwise they might both be merged.

**Comment by martin-g-it** [comment]
Onsolete due to PR 566

**Comment by stas-demydiuk** [comment]
Implemented in #458

**Pull request closed without merging**
