### PR TITLE
Please add new Moes BRT-100-TRV Thermostat support.

### PR DESCRIPTION
**Pull request by vladi1234**

### CODE REVIEW

**Comment by Alex-Jud** [comment]
Hello, I'm trying to correctly add my MOES BRT-100 to my domoticz. With the Zigbee2MQTT plugin I get a partial addition with some properties not accessible.

> 0x847127fffe9eb745: can not process binary item "eco_mode"
0x847127fffe9eb745: can not process numeric item "eco_temperature"
0x847127fffe9eb745: can not process numeric item "max_temperature"
0x847127fffe9eb745: can not process numeric item "min_temperature"
0x847127fffe9eb745: can not process binary item "window"
0x847127fffe9eb745: can not process binary item "boost_heating"
0x847127fffe9eb745: can not process numeric item "boost_heating_countdown"
0x847127fffe9eb745: can not process numeric item "boost_heating_countdown_time_set"

I have tried making the changes shown in this topic, but still get errors.

> 'onHeartbeat' failed 'AttributeError':''NoneType' object has no attribute 'onHeartbeat''.
 Exception traceback:
 ----> Line 306 in '/opt/domoticz/userdata/plugins/zigbee2mqtt/plugin.py', function onHeartbeat
 ----> Line 140 in '/opt/domoticz/userdata/plugins/zigbee2mqtt/plugin.py', function onHeartbeat
'onHeartbeat' failed 'AttributeError':''NoneType' object has no attribute 'onHeartbeat''.

With these changes do you manage to manage these properties?
What did I do wrong to make my plugin crash after making these changes?

**Comment by vladi1234** [comment]
Hi, 
I have corrected errors in file `adapters/moes/BRT100TRV.py` so that it works correctly.

**Comment by Alex-Jud** [comment]
Thanks for the update. this patch fix the 'onHeartbeat' fail.

But I've still can't acces to the eight properties. 
Must I re-pair this devices? Or is it a normal behavior?

**Comment by vladi1234** [comment]
Did you create this file? https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/pull/663/commits/8149b8976c6d318f0fcbd6225d565b486531b9a1

Did you edit this file correctly? https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/pull/663/commits/74a7ad2c180c15f8691936548166af84e0c5e9c3

**Comment by Alex-Jud** [comment]
Yes of course, but devices are paired before adding them, perhaps it's why they doesn't use all the arguments.
And if I remember well I have paired them with the domoticz autodiscover procedure.

I'll try a remove - re-pair process when I have some time to look at. And if it doesn't work I'll test with disabling HomeAssistant option in zigbee2mqtt

**Comment by vladi1234** [comment]
image

restart domoticz

image

**Comment by Alex-Jud** [comment]
My config is almost same as yours, I just keep track on link quality and my debug is on verbose. but I haven't 6 entries, I've 8. And I have still my errors logs for eco mode etc..
Capture
Capture2

I haven't do any test I talk about in my last comment. Stay tuned!

**Comment by WollyWonka** [comment]
Dear all,

I've added a fix to the TUYA-adapter TS0601_thermostat_1:


cd :~/dev-domoticz/plugins/zigbee2mqtt/adapters/tuya
sudo nano TS0601.py
	Add the bold lines:
```
		        self.devices.append(mode_switch)
		        self.devices.append(preset)
		        self.devices.append(week_format)
		        self.devices.append(SetPoint('spoint', 'current_heating_setpoint',' (Setpoint)'))
		        self.devices.append(SetPoint('sp_eco', 'eco_temperature',' (Eco Setpoint)'))
		        self.devices.append(SetPoint('sp_cmf', 'comfort_temperature',' (Comfort Setpoint)'))
		        self.devices.append(TemperatureSensor('temp', 'local_temperature',' (Temperature)'))
		        self.devices.append(LevelSwitch('level', 'position', ' (Valve position)'))
		        self.devices.append(OnOffSwitch('wnd', 'window_detection', ' (Window Detection)'))
		        self.devices.append(OnOffSwitch('child', 'child_lock', ' (Child Lock)'))	
		        **self.devices.append(OnOffSwitch('wndstate', 'window', ' (Window State)'))
		        self.devices.append(OnOffSwitch('maxtemp', 'max_temperature', ' (Maximum Temperature)'))
		        self.devices.append(OnOffSwitch('mintemp', 'min_temperature', ' (Minimum Temperature)'))
		        self.devices.append(OnOffSwitch('heatstate', 'heating', ' (Heating State)'))
		        self.devices.append(OnOffSwitch('heatbst', 'boost_heating', ' (Boost Heating)'))
                        self.devices.append(OnOffSwitch('heatbstcnt', 'boost_heating_countdown', ' (Boost Heating Countdown)'))**
```
		
sudo nano __init__.py
	Add the bold line:
```
		tuya_adapters = {
		    'TS0002': TS0002,                           # TuYa 2 gang switch
		    'TS0012': TS0012,                           # TuYa Smart light switch - 2 gang without neutral wire
		    'TS0013': TS0013,                           # TuYa Smart light switch - 3 gang without neutral wire
		    'TS0015': TS0015,                           # TuYa Multiprise with 4 AC outlets and 2 USB super charging ports (10A or 16A)
		    'TS0601_thermostat': TS0601,                # TuYa Radiator valve with thermostat		
		    **'TS0601_thermostat_1': TS0601,              # TuYa Radiator valve with thermostat**
		}
```

sudo service domoticz restart


Then it works like a charm!

Hopefully, Stanislav could add these fix to the code.

Many thanks in advance,
Wolly

**Comment by vladi1234** [comment]
Hello @WollyWonka,

Here we are discussing about completely different thermostat.

**Comment by WollyWonka** [comment]
> Hello @WollyWonka,
> 
> Here we are discussing about completely different thermostat.

My apologies. I've got some of the thermostats you are discussing as well. But was just struggling with a new one I had bought recently.
I'll copy paste my comment to a new issue.

**Comment by vladi1234** [comment]
Everything is fine, I've only been waiting for my Pull Request for 9 months when it will be included in the plugin, nothing is happening yet.

**Comment by WollyWonka** [comment]
That's shitty. It is probably a hobby project without any revenues but a pity to wait so long. 
Probably, stanislav could add additional admins to help.

**Comment by vladi1234** [comment]
I've already written for the TV02-Zigbee TRV converter at z2m and it also needs to be integrated into the plugin, but there's no point in making a pull request.

**Comment by vladi1234** [comment]
After 9 months maybe something can be born.

**Comment by stas-demydiuk** [comment]
Thanks for the contribution!

**Comment by vladi1234** [comment]
Thanks, I'll make another one for TV02 Zigbee then.

**Pull request merged**
